// mod any_cast_int;
mod boxed_closure;
// mod boxed_debug_cast;
// mod boxed_trait_fail;
mod boxed_trait;
// mod different_crates_fail;
mod different_crates;
// mod dyn_fn_mut;
// mod dyn_fn_once;
// mod dyn_fn_param_closure_capture;
// mod dyn_fn_param_closure;
// mod dyn_fn_param;
// mod dyn_main;
// mod encode_utf8;
// mod generic_duplicate_names_impl;
// mod generic_duplicate_names;
// mod nested_boxes_fail;
// mod nested_boxes;
// mod nested_closures;
// mod object_safe_generics;
// mod object_safe_trait;
// mod std_lib_add_duplicate;
// mod unsized_cast;
// mod unsized_rc_cast;
// mod vtable_duplicate_field_override;
// mod vtable_duplicate_fields;
// mod vtable_restrictions_fail_fixme;
// mod vtable_restrictions;
// mod vtable_size_align_drop;
